import { STATUS } from "@/enum";

export type ProjectManager = {
  id: string;
  name: string;
  email: string;
};
export type Project = {
  id: string;
  name: string;
  // project_manager: string;
  project_manager: ProjectManager;
  status: STATUS;
  last_updated: string;
  last_updated_note:string;
  resources: string[];
  start_date: string;
  end_date: string;
  estimated_cost: number;
};

export const projects: Project[] = [
  {
    id: "1",
    name: "Nice web app",
    project_manager: {
      id: "1",
      name: "James Turner",
      email: "james@gmail.com",
    },
    status: STATUS.ON_TRACK,
    last_updated: "31 Oct 2024, 06:00 PM",
    last_updated_note: "31 Oct 2024, 06:00 PM",
    resources: [
      "Research & Development",
      "Marketing",
      "Backend Development",
      "Frontend Development",
      "Data Analysis",
      "Project Management",
    ],
    start_date: "04 Jul 2024",
    end_date: "20 Jan 2024",
    estimated_cost: 6641,
  },
  {
    id: "2",
    name: "Begin web app",
    project_manager: {
      id: "2",
      name: "James2 Turner",
      email: "james2@gmail.com",
    },
    status: STATUS.ON_HOLD,
    last_updated: "13 Jun 2024, 08:18 AM",
    last_updated_note: "31 Oct 2024, 06:00 PM",
    resources: ["UX/UI Design", "Data Analysis", "Frontend Development"],
    start_date: "31 Jan 2024",
    end_date: "02 Jan 2024",
    estimated_cost: 19906,
  },
  {
    id: "3",
    name: "Important web app",
    project_manager: {
      id: "3",
      name: "James3 Turner",
      email: "james3@gmail.com",
    },
    status: STATUS.ON_TRACK,
    last_updated: "27 Nov 2024, 09:56 AM",
    last_updated_note: "31 Oct 2024, 06:00 PM",
    resources: [
      "Frontend Development",
      "QA",
      "Research & Development",
      "Infrastructure",
      "Project Management",
    ],
    start_date: "04 Aug 2024",
    end_date: "08 Jun 2024",
    estimated_cost: 6115,
  },
  {
    id: "4",
    name: "Federal web app",
    project_manager: {
      id: "1",
      name: "James Turner",
      email: "james@gmail.com",
    },
    status: STATUS.RISK,
    last_updated: "04 Nov 2024, 12:28 AM",
    last_updated_note: "31 Oct 2024, 06:00 PM",
    resources: [
      "Testing",
      "Project Management",
      "Backend Development",
      "Frontend Development",
      "Infrastructure",
      "Marketing",
    ],
    start_date: "01 Jun 2024",
    end_date: "14 Feb 2024",
    estimated_cost: 17790,
  },
  {
    id: "5",
    name: "Mrs web app",
    project_manager: {
      id: "1",
      name: "James Turner",
      email: "james@gmail.com",
    },
    status: STATUS.POTENTIAL_RISK,
    last_updated: "24 Nov 2024, 09:05 AM",
    last_updated_note: "31 Oct 2024, 06:00 PM",
    resources: [
      "Data Analysis",
      "Project Management",
      "UX/UI Design",
      "Infrastructure",
    ],
    start_date: "19 May 2024",
    end_date: "19 Feb 2024",
    estimated_cost: 10015,
  },
  {
    id: "6",
    name: "Building web app",
    project_manager: {
      id: "1",
      name: "James Turner",
      email: "james@gmail.com",
    },
    status: STATUS.ON_TRACK,
    last_updated: "12 Mar 2024, 05:52 AM",
    last_updated_note: "31 Oct 2024, 06:00 PM",
    resources: ["Data Analysis", "QA", "Infrastructure"],
    start_date: "09 Mar 2024",
    end_date: "09 Jun 2024",
    estimated_cost: 12500,
  },
  {
    id: "7",
    name: "Creative web app",
    project_manager: {
      id: "1",
      name: "James Turner",
      email: "james@gmail.com",
    },
    status: STATUS.ON_HOLD,
    last_updated: "20 Nov 2024, 04:27 PM",
    last_updated_note: "31 Oct 2024, 06:00 PM",
    resources: ["UX/UI Design", "Project Management", "Data Analysis"],
    start_date: "14 May 2024",
    end_date: "18 Oct 2024",
    estimated_cost: 10908,
  },
  {
    id: "8",
    name: "Future web app",
    project_manager: {
      id: "1",
      name: "James Turner",
      email: "james@gmail.com",
    },
    status: STATUS.POTENTIAL_RISK,
    last_updated: "03 Nov 2024, 10:32 AM",
    last_updated_note: "31 Oct 2024, 06:00 PM",
    resources: [
      "Backend Development",
      "Frontend Development",
      "Research & Development",
      "Testing",
    ],
    start_date: "25 Apr 2024",
    end_date: "05 Dec 2024",
    estimated_cost: 13472,
  },
  {
    id: "9",
    name: "Velocity web app",
    project_manager: {
      id: "1",
      name: "James Turner",
      email: "james@gmail.com",
    },
    status: STATUS.ON_TRACK,
    last_updated: "17 Oct 2024, 02:18 PM",
    last_updated_note: "31 Oct 2024, 06:00 PM",
    resources: ["QA", "Project Management", "Frontend Development"],
    start_date: "02 Mar 2024",
    end_date: "13 Jul 2024",
    estimated_cost: 8880,
  },
  {
    id: "10",
    name: "Everest web app",
    project_manager: {
      id: "1",
      name: "James Turner",
      email: "james@gmail.com",
    },
    status: STATUS.RISK,
    last_updated: "08 Aug 2024, 09:47 PM",
    last_updated_note: "31 Oct 2024, 06:00 PM",
    resources: [
      "Marketing",
      "Infrastructure",
      "Backend Development",
      "Testing",
    ],
    start_date: "12 Feb 2024",
    end_date: "20 May 2024",
    estimated_cost: 17990,
  },
  {
    id: "11",
    name: "Super web app",
    project_manager: {
      id: "1",
      name: "James Turner",
      email: "james@gmail.com",
    },
    status: STATUS.POTENTIAL_RISK,
    last_updated: "12 Jun 2024, 10:15 AM",
    last_updated_note: "31 Oct 2024, 06:00 PM",
    resources: [
      "QA",
      "Backend Development",
      "Research & Development",
      "Marketing",
      "Frontend Development",
      "Infrastructure",
    ],
    start_date: "13 Aug 2024",
    end_date: "17 Jan 2024",
    estimated_cost: 8423,
  },
  {
    id: "12",
    name: "Amount web app",
    project_manager: {
      id: "1",
      name: "James Turner",
      email: "james@gmail.com",
    },
    status: STATUS.ON_HOLD,
    last_updated: "06 Oct 2024, 12:45 AM",
    last_updated_note: "31 Oct 2024, 06:00 PM",
    resources: [
      "UX/UI Design",
      "Testing",
      "Data Analysis",
      "Research & Development",
      "Backend Development",
    ],
    start_date: "27 Oct 2024",
    end_date: "28 Oct 2024",
    estimated_cost: 6053,
  },
  {
    id: "13",
    name: "Single web app",
    project_manager: {
      id: "1",
      name: "James Turner",
      email: "james@gmail.com",
    },
    status: STATUS.RISK,
    last_updated: "10 Jul 2024, 12:37 AM",
    last_updated_note: "31 Oct 2024, 06:00 PM",
    resources: [
      "UX/UI Design",
      "Research & Development",
      "Backend Development",
    ],
    start_date: "16 Oct 2024",
    end_date: "17 Sep 2024",
    estimated_cost: 7271,
  },
  {
    id: "14",
    name: "Tree web app",
    project_manager: {
      id: "1",
      name: "James Turner",
      email: "james@gmail.com",
    },
    status: STATUS.ON_HOLD,
    last_updated: "28 Nov 2024, 08:34 AM",
    last_updated_note: "31 Oct 2024, 06:00 PM",
    resources: [
      "Marketing",
      "Research & Development",
      "Frontend Development",
      "Project Management",
    ],
    start_date: "17 May 2024",
    end_date: "16 Nov 2024",
    estimated_cost: 5063,
  },
  {
    id: "15",
    name: "Production web app",
    project_manager: {
      id: "1",
      name: "James Turner",
      email: "james@gmail.com",
    },
    status: STATUS.ON_TRACK,
    last_updated: "02 Jan 2024, 01:52 AM",
    last_updated_note: "31 Oct 2024, 06:00 PM",
    resources: [
      "Marketing",
      "Project Management",
      "Research & Development",
      "Testing",
      "UX/UI Design",
    ],
    start_date: "12 Jun 2024",
    end_date: "03 Sep 2024",
    estimated_cost: 13639,
  },
  {
    id: "16",
    name: "Mother web app",
    project_manager: {
      id: "1",
      name: "James Turner",
      email: "james@gmail.com",
    },
    status: STATUS.ON_HOLD,
    last_updated: "04 May 2024, 10:30 PM",
    last_updated_note: "31 Oct 2024, 06:00 PM",
    resources: [
      "Marketing",
      "Backend Development",
      "Testing",
      "Research & Development",
      "UX/UI Design",
    ],
    start_date: "07 Oct 2024",
    end_date: "25 Mar 2024",
    estimated_cost: 16905,
  },
  {
    id: "17",
    name: "Prime web app",
    project_manager: {
      id: "1",
      name: "James Turner",
      email: "james@gmail.com",
    },
    status: STATUS.POTENTIAL_RISK,
    last_updated: "02 Nov 2024, 08:12 AM",
    last_updated_note: "31 Oct 2024, 06:00 PM",
    resources: [
      "Frontend Development",
      "Backend Development",
      "QA",
      "Project Management",
      "Research & Development",
    ],
    start_date: "20 Jul 2024",
    end_date: "25 Nov 2024",
    estimated_cost: 11234,
  },
  {
    id: "18",
    name: "Tech web app",
    project_manager: {
      id: "1",
      name: "James Turner",
      email: "james@gmail.com",
    },
    status: STATUS.RISK,
    last_updated: "15 Aug 2024, 06:23 AM",
    last_updated_note: "31 Oct 2024, 06:00 PM",
    resources: [
      "Marketing",
      "Backend Development",
      "Data Analysis",
      "Research & Development",
    ],
    start_date: "01 Apr 2024",
    end_date: "03 Jul 2024",
    estimated_cost: 9463,
  },
  {
    id: "19",
    name: "Bold web app",
    project_manager: {
      id: "1",
      name: "James Turner",
      email: "james@gmail.com",
    },
    status: STATUS.ON_TRACK,
    last_updated: "07 Sep 2024, 02:57 PM",
    last_updated_note: "31 Oct 2024, 06:00 PM",
    resources: ["Frontend Development", "Project Management", "QA"],
    start_date: "11 Dec 2023",
    end_date: "15 Jun 2024",
    estimated_cost: 13021,
  },
  {
    id: "20",
    name: "Space web app",
    project_manager: {
      id: "1",
      name: "James Turner",
      email: "james@gmail.com",
    },
    status: STATUS.ON_HOLD,
    last_updated: "18 Apr 2024, 09:18 AM",
    last_updated_note: "31 Oct 2024, 06:00 PM",
    resources: [
      "Backend Development",
      "Research & Development",
      "Marketing",
      "UX/UI Design",
    ],
    start_date: "17 Jan 2024",
    end_date: "30 Aug 2024",
    estimated_cost: 10891,
  },
  {
    id: "21",
    name: "Galaxy web app",
    project_manager: {
      id: "1",
      name: "James Turner",
      email: "james@gmail.com",
    },
    status: STATUS.ON_TRACK,
    last_updated: "23 Nov 2024, 11:30 AM",
    last_updated_note: "31 Oct 2024, 06:00 PM",
    resources: [
      "Infrastructure",
      "Frontend Development",
      "QA",
      "Project Management",
      "Research & Development",
    ],
    start_date: "22 Jun 2024",
    end_date: "14 Dec 2024",
    estimated_cost: 9250,
  },
  {
    id: "22",
    name: "Dragon web app",
    project_manager: {
      id: "1",
      name: "James Turner",
      email: "james@gmail.com",
    },
    status: STATUS.POTENTIAL_RISK,
    last_updated: "27 Sep 2024, 05:10 PM",
    last_updated_note: "31 Oct 2024, 06:00 PM",
    resources: [
      "Backend Development",
      "Testing",
      "Project Management",
      "UX/UI Design",
    ],
    start_date: "03 Apr 2024",
    end_date: "28 Jan 2024",
    estimated_cost: 13765,
  },
  {
    id: "23",
    name: "Titan web app",
    project_manager: {
      id: "1",
      name: "James Turner",
      email: "james@gmail.com",
    },
    status: STATUS.RISK,
    last_updated: "13 May 2024, 07:45 AM",
    last_updated_note: "31 Oct 2024, 06:00 PM",
    resources: [
      "Project Management",
      "Marketing",
      "Frontend Development",
      "QA",
    ],
    start_date: "08 Jan 2024",
    end_date: "18 Mar 2024",
    estimated_cost: 15632,
  },
  {
    id: "24",
    name: "Ocean web app",
    project_manager: {
      id: "1",
      name: "James Turner",
      email: "james@gmail.com",
    },
    status: STATUS.ON_HOLD,
    last_updated: "19 Nov 2024, 12:14 PM",
    last_updated_note: "31 Oct 2024, 06:00 PM",
    resources: ["Frontend Development", "Data Analysis", "Infrastructure"],
    start_date: "15 Feb 2024",
    end_date: "22 Jul 2024",
    estimated_cost: 12345,
  },
  {
    id: "25",
    name: "Sun web app",
    project_manager: {
      id: "1",
      name: "James Turner",
      email: "james@gmail.com",
    },
    status: STATUS.POTENTIAL_RISK,
    last_updated: "01 Sep 2024, 11:01 AM",
    last_updated_note: "31 Oct 2024, 06:00 PM",
    resources: ["QA", "Backend Development", "Research & Development"],
    start_date: "12 May 2024",
    end_date: "06 Dec 2024",
    estimated_cost: 12456,
  },
  {
    id: "26",
    name: "Cosmos web app",
    project_manager: {
      id: "1",
      name: "James Turner",
      email: "james@gmail.com",
    },
    status: STATUS.RISK,
    last_updated: "05 Aug 2024, 03:12 PM",
    last_updated_note: "31 Oct 2024, 06:00 PM",
    resources: [
      "Marketing",
      "Backend Development",
      "Frontend Development",
      "Project Management",
    ],
    start_date: "29 Mar 2024",
    end_date: "21 Dec 2024",
    estimated_cost: 14234,
  },

  {
    id: "41",
    name: "Meteor web app",
    project_manager: {
      id: "1",
      name: "James Turner",
      email: "james@gmail.com",
    },
    status: STATUS.POTENTIAL_RISK,
    last_updated: "06 Dec 2024, 10:13 PM",
    last_updated_note: "31 Oct 2024, 06:00 PM",
    resources: [
      "Infrastructure",
      "Data Analysis",
      "Project Management",
      "Frontend Development",
    ],
    start_date: "22 Mar 2024",
    end_date: "20 Nov 2024",
    estimated_cost: 12745,
  },
  {
    id: "42",
    name: "Planet web app",
    project_manager: {
      id: "1",
      name: "James Turner",
      email: "james@gmail.com",
    },
    status: STATUS.RISK,
    last_updated: "15 May 2024, 01:43 PM",
    last_updated_note: "31 Oct 2024, 06:00 PM",
    resources: ["Marketing", "Project Management", "Frontend Development"],
    start_date: "04 Oct 2024",
    end_date: "16 Feb 2024",
    estimated_cost: 9932,
  },
  {
    id: "43",
    name: "Sunset web app",
    project_manager: {
      id: "1",
      name: "James Turner",
      email: "james@gmail.com",
    },
    status: STATUS.ON_HOLD,
    last_updated: "02 Oct 2024, 02:30 PM",
    last_updated_note: "31 Oct 2024, 06:00 PM",
    resources: [
      "Backend Development",
      "Frontend Development",
      "Research & Development",
    ],
    start_date: "14 Mar 2024",
    end_date: "02 Dec 2024",
    estimated_cost: 11944,
  },
];
